name: CI/CD Pipeline for Terraform and Application Deployment

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual runs

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    # Initialize Terraform
    - name: Terraform Init
      run: terraform -chdir=terraform init

    # Validate Terraform
    - name: Terraform Validate
      run: terraform -chdir=terraform validate

    # Plan Terraform Changes
    - name: Terraform Plan
      run: terraform -chdir=terraform plan

    # Apply Terraform Changes
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' || github.ref_name == 'main'
      run: terraform -chdir=terraform apply -auto-approve

  deploy_app:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: terraform # Ensure this runs after Terraform job

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Deploy Application Code to EC2
    - name: Deploy App to EC2
      run: |
        chmod +x scripts/deploy.sh
        ./scripts/deploy.sh
